/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WatchlistRouteImport } from './routes/watchlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lists': typeof ListsRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lists': typeof ListsRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diary': typeof DiaryRoute
  '/lists': typeof ListsRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diary' | '/lists' | '/movies' | '/profile' | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diary' | '/lists' | '/movies' | '/profile' | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/diary'
    | '/lists'
    | '/movies'
    | '/profile'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiaryRoute: typeof DiaryRoute
  ListsRoute: typeof ListsRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiaryRoute: DiaryRoute,
  ListsRoute: ListsRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
